apiVersion: batch/v1
kind: Job
metadata:
  name: create-db-job
  namespace: oficina-homolog
spec:
  template:
    spec:
      containers:
      - name: psql
        image: postgres:15
        command: ["sh", "-c"]
        args:
        - export PGPASSWORD="$DB_PASSWORD" && psql -h "$DB_HOST" -U "$DB_USER" -d "$DB_NAME" -f /sql/create-db.sql
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: oficina-cardozo-db-secret
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: oficina-cardozo-db-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: oficina-cardozo-db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: oficina-cardozo-db-secret
              key: DB_NAME
        volumeMounts:
        - name: sql-script
          mountPath: /sql
      restartPolicy: Never
      volumes:
      - name: sql-script
        configMap:
          name: create-db-sql
  backoffLimit: 1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: create-db-sql
  namespace: oficina-homolog
data:
  create-db.sql: |
    DROP TABLE IF EXISTS "__EFMigrationsHistory" CASCADE;
    DROP TABLE IF EXISTS "OFICINA_ORDEM_SERVICO_SERVICO" CASCADE;
    DROP TABLE IF EXISTS "OFICINA_ORDEM_SERVICO_PECA" CASCADE;
    DROP TABLE IF EXISTS "OFICINA_ORCAMENTO" CASCADE;
    DROP TABLE IF EXISTS "OFICINA_ORDEM_SERVICO" CASCADE;
    DROP TABLE IF EXISTS "OFICINA_VEICULO" CASCADE;
    DROP TABLE IF EXISTS "OFICINA_USUARIO" CASCADE;
    DROP TABLE IF EXISTS "OFICINA_SERVICO" CASCADE;
    DROP TABLE IF EXISTS "OFICINA_PECA" CASCADE;
    DROP TABLE IF EXISTS "OFICINA_ORDEM_SERVICO_STATUS" CASCADE;
    DROP TABLE IF EXISTS "OFICINA_ORCAMENTO_STATUS" CASCADE;
    DROP TABLE IF EXISTS "OFICINA_CLIENTE" CASCADE;
    -- Refatoração: IDs auto-incremento, tipos e constraints revisados para evitar erros de insert/update

    CREATE TABLE IF NOT EXISTS "OFICINA_CLIENTE" (
        "ID" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        "NOME" TEXT NOT NULL,
        "CPF_CNPJ" TEXT NOT NULL,
        "TELEFONE_PRINCIPAL" TEXT NOT NULL,
        "EMAIL_PRINCIPAL" TEXT NOT NULL,
        "ENDERECO_PRINCIPAL" TEXT NOT NULL
    );

    CREATE TABLE IF NOT EXISTS "OFICINA_ORCAMENTO_STATUS" (
        "ID" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        "DESCRICAO" TEXT
    );

    CREATE TABLE IF NOT EXISTS "OFICINA_ORDEM_SERVICO_STATUS" (
        "ID" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        "DESCRICAO" TEXT
    );

    CREATE TABLE IF NOT EXISTS "OFICINA_PECA" (
        "ID" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        "NOME_PECA" TEXT NOT NULL,
        "CODIGO_IDENTIFICADOR" TEXT NOT NULL,
        "PRECO" NUMERIC(12,2) NOT NULL,
        "QTD_ESTOQUE" INTEGER NOT NULL,
        "QTD_MINIMA" INTEGER NOT NULL,
        "UNIDADE_MEDIDA" TEXT NOT NULL,
        "LOCALIZACAO_ESTOQUE" TEXT,
        "OBSERVACOES" TEXT
    );

    CREATE TABLE IF NOT EXISTS "OFICINA_SERVICO" (
        "ID" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        "NOME_SERVICO" TEXT NOT NULL,
        "PRECO" NUMERIC(12,2) NOT NULL,
        "TEMPO_ESTIMADO_EXECUCAO" INTEGER NOT NULL,
        "DESCRICAO_DETALHADA_SERVICO" TEXT NOT NULL,
        "FREQUENCIA_RECOMENDADA" TEXT NOT NULL
    );

    CREATE TABLE IF NOT EXISTS "OFICINA_USUARIO" (
        "ID" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        "NOME_USUARIO" TEXT NOT NULL,
        "EMAIL" TEXT NOT NULL,
        "HASH_SENHA" TEXT NOT NULL,
        "COMPLEXIDADE" TEXT NOT NULL,
        "DATA_CRIACAO" TIMESTAMP NOT NULL
    );

    CREATE TABLE IF NOT EXISTS "OFICINA_VEICULO" (
        "ID" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        "ID_CLIENTE" INTEGER NOT NULL,
        "PLACA" TEXT NOT NULL,
        "MARCA_MODELO" TEXT NOT NULL,
        "ANO_FABRICACAO" INTEGER NOT NULL,
        "COR" TEXT NOT NULL,
        "TIPO_COMBUSTIVEL" TEXT NOT NULL,
        CONSTRAINT "FK_OFICINA_VEICULO_OFICINA_CLIENTE_ID_CLIENTE" FOREIGN KEY ("ID_CLIENTE") REFERENCES "OFICINA_CLIENTE" ("ID") ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS "OFICINA_ORDEM_SERVICO" (
        "ID" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        "DATA_SOLICITACAO" TIMESTAMP NOT NULL,
        "ID_VEICULO" INTEGER NOT NULL,
        "ID_STATUS" INTEGER NOT NULL,
        "DATA_FINALIZACAO" TIMESTAMP,
        "DATA_ENTREGA" TIMESTAMP,
        CONSTRAINT "FK_OFICINA_ORDEM_SERVICO_OFICINA_ORDEM_SERVICO_STATUS_ID_STATUS" FOREIGN KEY ("ID_STATUS") REFERENCES "OFICINA_ORDEM_SERVICO_STATUS" ("ID") ON DELETE CASCADE,
        CONSTRAINT "FK_OFICINA_ORDEM_SERVICO_OFICINA_VEICULO_ID_VEICULO" FOREIGN KEY ("ID_VEICULO") REFERENCES "OFICINA_VEICULO" ("ID") ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS "OFICINA_ORCAMENTO" (
        "ID" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        "DATA_ORCAMENTO" TIMESTAMP NOT NULL,
        "ID_ORDEM_SERVICO" INTEGER NOT NULL,
        "ID_STATUS" INTEGER NOT NULL,
        CONSTRAINT "FK_OFICINA_ORCAMENTO_OFICINA_ORCAMENTO_STATUS_ID_STATUS" FOREIGN KEY ("ID_STATUS") REFERENCES "OFICINA_ORCAMENTO_STATUS" ("ID") ON DELETE CASCADE,
        CONSTRAINT "FK_OFICINA_ORCAMENTO_OFICINA_ORDEM_SERVICO_ID_ORDEM_SERVICO" FOREIGN KEY ("ID_ORDEM_SERVICO") REFERENCES "OFICINA_ORDEM_SERVICO" ("ID") ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS "OFICINA_ORDEM_SERVICO_PECA" (
        "ID_PECA" INTEGER NOT NULL,
        "ID_ORDEM_SERVICO" INTEGER NOT NULL,
        "QUANTIDADE" INTEGER NOT NULL,
        "VALOR_UNITARIO" NUMERIC(12,2),
        CONSTRAINT "PK_OFICINA_ORDEM_SERVICO_PECA" PRIMARY KEY ("ID_ORDEM_SERVICO", "ID_PECA"),
        CONSTRAINT "FK_OFICINA_ORDEM_SERVICO_PECA_OFICINA_ORDEM_SERVICO_ID_ORDEM_SERVICO" FOREIGN KEY ("ID_ORDEM_SERVICO") REFERENCES "OFICINA_ORDEM_SERVICO" ("ID") ON DELETE CASCADE,
        CONSTRAINT "FK_OFICINA_ORDEM_SERVICO_PECA_OFICINA_PECA_ID_PECA" FOREIGN KEY ("ID_PECA") REFERENCES "OFICINA_PECA" ("ID") ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS "OFICINA_ORDEM_SERVICO_SERVICO" (
        "ID_ORDEM_SERVICO" INTEGER NOT NULL,
        "ID_SERVICO" INTEGER NOT NULL,
        "VALOR_APLICADO" NUMERIC(12,2),
        CONSTRAINT "PK_OFICINA_ORDEM_SERVICO_SERVICO" PRIMARY KEY ("ID_ORDEM_SERVICO", "ID_SERVICO"),
        CONSTRAINT "FK_OFICINA_ORDEM_SERVICO_SERVICO_OFICINA_ORDEM_SERVICO_ID_ORDEM_SERVICO" FOREIGN KEY ("ID_ORDEM_SERVICO") REFERENCES "OFICINA_ORDEM_SERVICO" ("ID") ON DELETE CASCADE,
        CONSTRAINT "FK_OFICINA_ORDEM_SERVICO_SERVICO_OFICINA_SERVICO_ID_SERVICO" FOREIGN KEY ("ID_SERVICO") REFERENCES "OFICINA_SERVICO" ("ID") ON DELETE CASCADE
    );

    -- Índices e inserts de status mantidos conforme original, podem ser revisados conforme necessidade de negócio


