apiVersion: batch/v1
kind: Job
metadata:
  name: create-db-job
  namespace: oficina-homolog
spec:
  template:
    spec:
      containers:
      - name: psql
        image: postgres:15
        command: ["sh", "-c"]
        args:
        - |
            {
                export PGPASSWORD="$DB_PASSWORD"
                if psql -h "$DB_HOST" -U "$DB_USER" -d "$DB_NAME" -c '\dt' | grep -q OFICINA_CLIENTE; then
                    echo 'Banco já existe, pulando criação.'
                    exit 0
                fi
                psql -h "$DB_HOST" -U "$DB_USER" -d "$DB_NAME" -f /sql/create-db.sql
            }
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: oficina-cardozo-db-secret
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: oficina-cardozo-db-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: oficina-cardozo-db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: oficina-cardozo-db-secret
              key: DB_NAME
        volumeMounts:
        - name: sql-script
          mountPath: /sql
      restartPolicy: Never
      volumes:
      - name: sql-script
        configMap:
          name: create-db-sql
  backoffLimit: 1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: create-db-sql
  namespace: oficina-homolog
data:
  create-db.sql: |
    CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
        "MigrationId" character varying(150) NOT NULL,
        "ProductVersion" character varying(32) NOT NULL,
        CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
    );

    START TRANSACTION;

    DO $EF$
    BEGIN
        IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011145222_InitialCreate') THEN
        CREATE TABLE "OFICINA_CLIENTE" (
            "ID" INTEGER NOT NULL,
            "NOME" TEXT NOT NULL,
            "CPF_CNPJ" TEXT NOT NULL,
            "TELEFONE_PRINCIPAL" TEXT NOT NULL,
            "EMAIL_PRINCIPAL" TEXT NOT NULL,
            "ENDERECO_PRINCIPAL" TEXT NOT NULL,
            CONSTRAINT "PK_OFICINA_CLIENTE" PRIMARY KEY ("ID")
        );
        END IF;
    END $EF$;

    DO $EF$
    BEGIN
        IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011145222_InitialCreate') THEN
        CREATE TABLE "OFICINA_ORCAMENTO_STATUS" (
            "ID" INTEGER NOT NULL,
            "DESCRICAO" TEXT,
            CONSTRAINT "PK_OFICINA_ORCAMENTO_STATUS" PRIMARY KEY ("ID")
        );
        END IF;
    END $EF$;

    DO $EF$
    BEGIN
        IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011145222_InitialCreate') THEN
        CREATE TABLE "OFICINA_ORDEM_SERVICO_STATUS" (
            "ID" INTEGER NOT NULL,
            "DESCRICAO" TEXT,
            CONSTRAINT "PK_OFICINA_ORDEM_SERVICO_STATUS" PRIMARY KEY ("ID")
        );
        END IF;
    END $EF$;

    DO $EF$
    BEGIN
        IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011145222_InitialCreate') THEN
        CREATE TABLE "OFICINA_PECA" (
            "ID" INTEGER NOT NULL,
            "NOME_PECA" TEXT NOT NULL,
            "CODIGO_IDENTIFICADOR" TEXT NOT NULL,
            "PRECO" TEXT NOT NULL,
            "QTD_ESTOQUE" INTEGER NOT NULL,
            "QTD_MINIMA" INTEGER NOT NULL,
            "UNIDADE_MEDIDA" TEXT NOT NULL,
            "LOCALIZACAO_ESTOQUE" TEXT,
            "OBSERVACOES" TEXT,
            CONSTRAINT "PK_OFICINA_PECA" PRIMARY KEY ("ID")
        );
        END IF;
    END $EF$;

    DO $EF$
    BEGIN
        IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011145222_InitialCreate') THEN
        CREATE TABLE "OFICINA_SERVICO" (
            "ID" INTEGER NOT NULL,
            "NOME_SERVICO" TEXT NOT NULL,
            "PRECO" TEXT NOT NULL,
            "TEMPO_ESTIMADO_EXECUCAO" INTEGER NOT NULL,
            "DESCRICAO_DETALHADA_SERVICO" TEXT NOT NULL,
            "FREQUENCIA_RECOMENDADA" TEXT NOT NULL,
            CONSTRAINT "PK_OFICINA_SERVICO" PRIMARY KEY ("ID")
        );
        END IF;
    END $EF$;

    DO $EF$
    BEGIN
        IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011145222_InitialCreate') THEN
        CREATE TABLE "OFICINA_USUARIO" (
            "ID" INTEGER NOT NULL,
            "NOME_USUARIO" TEXT NOT NULL,
            "EMAIL" TEXT NOT NULL,
            "HASH_SENHA" TEXT NOT NULL,
            "COMPLEXIDADE" TEXT NOT NULL,
            "DATA_CRIACAO" INTEGER NOT NULL,
            CONSTRAINT "PK_OFICINA_USUARIO" PRIMARY KEY ("ID")
        );
        END IF;
    END $EF$;

    DO $EF$
    BEGIN
        IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011145222_InitialCreate') THEN
        CREATE TABLE "OFICINA_VEICULO" (
            "ID" INTEGER NOT NULL,
            "ID_CLIENTE" INTEGER NOT NULL,
            "PLACA" TEXT NOT NULL,
            "MARCA_MODELO" TEXT NOT NULL,
            "ANO_FABRICACAO" INTEGER NOT NULL,
            "COR" TEXT NOT NULL,
            "TIPO_COMBUSTIVEL" TEXT NOT NULL,
            CONSTRAINT "PK_OFICINA_VEICULO" PRIMARY KEY ("ID"),
            CONSTRAINT "FK_OFICINA_VEICULO_OFICINA_CLIENTE_ID_CLIENTE" FOREIGN KEY ("ID_CLIENTE") REFERENCES "OFICINA_CLIENTE" ("ID") ON DELETE CASCADE
        );
        END IF;
    END $EF$;

    DO $EF$
    BEGIN
        IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011145222_InitialCreate') THEN
        CREATE TABLE "OFICINA_ORDEM_SERVICO" (
            "ID" INTEGER NOT NULL,
            "DATA_SOLICITACAO" INTEGER NOT NULL,
            "ID_VEICULO" INTEGER NOT NULL,
            "ID_STATUS" INTEGER NOT NULL,
            "DATA_FINALIZACAO" INTEGER,
            "DATA_ENTREGA" INTEGER,
            CONSTRAINT "PK_OFICINA_ORDEM_SERVICO" PRIMARY KEY ("ID"),
            CONSTRAINT "FK_OFICINA_ORDEM_SERVICO_OFICINA_ORDEM_SERVICO_STATUS_ID_STATUS" FOREIGN KEY ("ID_STATUS") REFERENCES "OFICINA_ORDEM_SERVICO_STATUS" ("ID") ON DELETE CASCADE,
            CONSTRAINT "FK_OFICINA_ORDEM_SERVICO_OFICINA_VEICULO_ID_VEICULO" FOREIGN KEY ("ID_VEICULO") REFERENCES "OFICINA_VEICULO" ("ID") ON DELETE CASCADE
        );
        END IF;
    END $EF$;

    DO $EF$
    BEGIN
        IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011145222_InitialCreate') THEN
        CREATE TABLE "OFICINA_ORCAMENTO" (
            "ID" INTEGER NOT NULL,
            "DATA_ORCAMENTO" INTEGER NOT NULL,
            "ID_ORDEM_SERVICO" INTEGER NOT NULL,
            "ID_STATUS" INTEGER NOT NULL,
            CONSTRAINT "PK_OFICINA_ORCAMENTO" PRIMARY KEY ("ID"),
            CONSTRAINT "FK_OFICINA_ORCAMENTO_OFICINA_ORCAMENTO_STATUS_ID_STATUS" FOREIGN KEY ("ID_STATUS") REFERENCES "OFICINA_ORCAMENTO_STATUS" ("ID") ON DELETE CASCADE,
            CONSTRAINT "FK_OFICINA_ORCAMENTO_OFICINA_ORDEM_SERVICO_ID_ORDEM_SERVICO" FOREIGN KEY ("ID_ORDEM_SERVICO") REFERENCES "OFICINA_ORDEM_SERVICO" ("ID") ON DELETE CASCADE
        );
        END IF;
    END $EF$;

    DO $EF$
    BEGIN
        IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011145222_InitialCreate') THEN
        CREATE TABLE "OFICINA_ORDEM_SERVICO_PECA" (
            "ID_PECA" INTEGER NOT NULL,
            "ID_ORDEM_SERVICO" INTEGER NOT NULL,
            "QUANTIDADE" INTEGER NOT NULL,
            "VALOR_UNITARIO" TEXT,
            CONSTRAINT "PK_OFICINA_ORDEM_SERVICO_PECA" PRIMARY KEY ("ID_ORDEM_SERVICO", "ID_PECA"),
            CONSTRAINT "FK_OFICINA_ORDEM_SERVICO_PECA_OFICINA_ORDEM_SERVICO_ID_ORDEM_SERVICO" FOREIGN KEY ("ID_ORDEM_SERVICO") REFERENCES "OFICINA_ORDEM_SERVICO" ("ID") ON DELETE CASCADE,
            CONSTRAINT "FK_OFICINA_ORDEM_SERVICO_PECA_OFICINA_PECA_ID_PECA" FOREIGN KEY ("ID_PECA") REFERENCES "OFICINA_PECA" ("ID") ON DELETE CASCADE
        );
        END IF;
    END $EF$;

    DO $EF$
    BEGIN
        IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011145222_InitialCreate') THEN
        CREATE TABLE "OFICINA_ORDEM_SERVICO_SERVICO" (
            "ID_ORDEM_SERVICO" INTEGER NOT NULL,
            "ID_SERVICO" INTEGER NOT NULL,
            "VALOR_APLICADO" TEXT,
            CONSTRAINT "PK_OFICINA_ORDEM_SERVICO_SERVICO" PRIMARY KEY ("ID_ORDEM_SERVICO", "ID_SERVICO"),
            CONSTRAINT "FK_OFICINA_ORDEM_SERVICO_SERVICO_OFICINA_ORDEM_SERVICO_ID_ORDEM_SERVICO" FOREIGN KEY ("ID_ORDEM_SERVICO") REFERENCES "OFICINA_ORDEM_SERVICO" ("ID") ON DELETE CASCADE,
            CONSTRAINT "FK_OFICINA_ORDEM_SERVICO_SERVICO_OFICINA_SERVICO_ID_SERVICO" FOREIGN KEY ("ID_SERVICO") REFERENCES "OFICINA_SERVICO" ("ID") ON DELETE CASCADE
        );
        END IF;
    END $EF$;

    DO $EF$
    BEGIN
        IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011145222_InitialCreate') THEN
        INSERT INTO "OFICINA_ORCAMENTO_STATUS" ("ID", "DESCRICAO")
        VALUES (1, 'Criado');
        INSERT INTO "OFICINA_ORCAMENTO_STATUS" ("ID", "DESCRICAO")
        VALUES (2, 'Pendente aprovacao');
        INSERT INTO "OFICINA_ORCAMENTO_STATUS" ("ID", "DESCRICAO")
        VALUES (3, 'Aprovado');
        INSERT INTO "OFICINA_ORCAMENTO_STATUS" ("ID", "DESCRICAO")
        VALUES (4, 'Rejeitado');
        INSERT INTO "OFICINA_ORCAMENTO_STATUS" ("ID", "DESCRICAO")
        VALUES (5, 'Em elaboracao');
        END IF;
    END $EF$;

    DO $EF$
    BEGIN
        IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011145222_InitialCreate') THEN
        INSERT INTO "OFICINA_ORDEM_SERVICO_STATUS" ("ID", "DESCRICAO")
        VALUES (1, 'Recebida');
        INSERT INTO "OFICINA_ORDEM_SERVICO_STATUS" ("ID", "DESCRICAO")
        VALUES (2, 'Em diagnostico');
        INSERT INTO "OFICINA_ORDEM_SERVICO_STATUS" ("ID", "DESCRICAO")
        VALUES (3, 'Aguardando aprovacao');
        INSERT INTO "OFICINA_ORDEM_SERVICO_STATUS" ("ID", "DESCRICAO")
        VALUES (4, 'Em execucao');
        INSERT INTO "OFICINA_ORDEM_SERVICO_STATUS" ("ID", "DESCRICAO")
        VALUES (5, 'Finalizada');
        INSERT INTO "OFICINA_ORDEM_SERVICO_STATUS" ("ID", "DESCRICAO")
        VALUES (6, 'Entregue');
        INSERT INTO "OFICINA_ORDEM_SERVICO_STATUS" ("ID", "DESCRICAO")
        VALUES (7, 'Em elaboracao');
        INSERT INTO "OFICINA_ORDEM_SERVICO_STATUS" ("ID", "DESCRICAO")
        VALUES (8, 'Cancelada');
        INSERT INTO "OFICINA_ORDEM_SERVICO_STATUS" ("ID", "DESCRICAO")
        VALUES (9, 'Devolvida');
        END IF;
    END $EF$;

    DO $EF$
    BEGIN
        IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011145222_InitialCreate') THEN
        CREATE INDEX "IX_OFICINA_ORCAMENTO_ID_ORDEM_SERVICO" ON "OFICINA_ORCAMENTO" ("ID_ORDEM_SERVICO");
        END IF;
    END $EF$;

    DO $EF$
    BEGIN
        IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011145222_InitialCreate') THEN
        CREATE INDEX "IX_OFICINA_ORCAMENTO_ID_STATUS" ON "OFICINA_ORCAMENTO" ("ID_STATUS");
        END IF;
    END $EF$;

    DO $EF$
    BEGIN
        IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011145222_InitialCreate') THEN
        CREATE INDEX "IX_OFICINA_ORDEM_SERVICO_ID_STATUS" ON "OFICINA_ORDEM_SERVICO" ("ID_STATUS");
        END IF;
    END $EF$;

    DO $EF$
    BEGIN
        IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011145222_InitialCreate') THEN
        CREATE INDEX "IX_OFICINA_ORDEM_SERVICO_ID_VEICULO" ON "OFICINA_ORDEM_SERVICO" ("ID_VEICULO");
        END IF;
    END $EF$;

    DO $EF$
    BEGIN
        IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011145222_InitialCreate') THEN
        CREATE INDEX "IX_OFICINA_ORDEM_SERVICO_PECA_ID_PECA" ON "OFICINA_ORDEM_SERVICO_PECA" ("ID_PECA");
        END IF;
    END $EF$;

    DO $EF$
    BEGIN
        IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011145222_InitialCreate') THEN
        CREATE INDEX "IX_OFICINA_ORDEM_SERVICO_SERVICO_ID_SERVICO" ON "OFICINA_ORDEM_SERVICO_SERVICO" ("ID_SERVICO");
        END IF;
    END $EF$;

    DO $EF$
    BEGIN
        IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011145222_InitialCreate') THEN
        CREATE INDEX "IX_OFICINA_VEICULO_ID_CLIENTE" ON "OFICINA_VEICULO" ("ID_CLIENTE");
        END IF;
    END $EF$;

    DO $EF$
    BEGIN
        IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011145222_InitialCreate') THEN
        INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
        VALUES ('20251011145222_InitialCreate', '8.0.11');
        END IF;
    END $EF$;
    COMMIT;
