apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"oficina-cardozo-api"},"name":"oficina-cardozo-api","namespace":"oficina-homolog"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"oficina-cardozo-api"}},"template":{"metadata":{"annotations":{"ad.datadoghq.com/api.logs":"[{\"source\":\"csharp\",\"service\":\"oficina-cardozo-api\"}]"},"labels":{"app":"oficina-cardozo-api"}},"spec":{"containers":[{"env":[{"name":"POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}},{"name":"DATADOG_API_KEY","valueFrom":{"secretKeyRef":{"key":"api_key","name":"datadog-secret"}}},{"name":"DATADOG_API_KEY_AGENT","valueFrom":{"secretKeyRef":{"key":"api-key","name":"datadog-agent"}}},{"name":"DATADOG_SITE","value":"us5.datadoghq.com"}],"envFrom":[{"configMapRef":{"name":"oficina-cardozo-config"}},{"configMapRef":{"name":"datadog-config"}},{"secretRef":{"name":"oficina-cardozo-db-secret"}},{"secretRef":{"name":"oficina-cardozo-secrets"}},{"secretRef":{"name":"datadog-secret"}}],"image":"marciocardozodev/oficinacardozo-api-web:latest","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":5,"httpGet":{"path":"/Health/live","port":8080},"initialDelaySeconds":30,"periodSeconds":10,"timeoutSeconds":3},"name":"api","ports":[{"containerPort":8080}],"readinessProbe":{"failureThreshold":5,"httpGet":{"path":"/Health/live","port":8080},"initialDelaySeconds":10,"periodSeconds":5,"timeoutSeconds":3},"resources":{"limits":{"cpu":"500m","memory":"512Mi"},"requests":{"cpu":"100m","memory":"256Mi"}}}]}}}}
  creationTimestamp: "2026-02-09T21:55:55Z"
  generation: 2
  labels:
    app: oficina-cardozo-api
  name: oficina-cardozo-api
  namespace: oficina-homolog
  resourceVersion: "12151"
  uid: 9b81b15a-f1eb-49b8-b4c3-2c1603c16f88
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: oficina-cardozo-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      # ...existing code...
      labels:
        app: oficina-cardozo-api
    spec:
      containers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        # ...existing code...
        envFrom:
        - configMapRef:
            name: oficina-cardozo-config
        # ...existing code...
        - secretRef:
            name: oficina-cardozo-db-secret
        - secretRef:
            name: oficina-cardozo-secrets
        # ...existing code...
        image: marciocardozodev/oficinacardozo-api-web:36f2384c51816c6f883c245efb852adb4e881574
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /Health/live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        name: api
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /Health/live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2026-02-09T21:55:55Z"
    lastUpdateTime: "2026-02-09T21:55:55Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2026-02-09T22:56:03Z"
    lastUpdateTime: "2026-02-09T22:56:03Z"
    message: ReplicaSet "oficina-cardozo-api-549b67b99f" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 2
  replicas: 2
  unavailableReplicas: 2
  updatedReplicas: 1
